<?php

use Air\Model\ModelAbstract;
use Air\Crud\Locale;

/** @var array $filter */
$filter = $this->filter;

/** @var ModelAbstract $model */
$model = new $filter['model']();

/** @var string $field */
$field = $filter['field'] ?? null;

if (!$field && $model->getMeta()->hasProperty('title')) {
  $field = 'title';
}

if (isset($filter['title'])) {
  $title = $filter['title'] . ' (' . Locale::t('All') . ')';
} else {
  $title = Locale::t('All');
}

$hasImage = $model->getMeta()->hasProperty('image');
$hasEnabled = $model->getMeta()->hasProperty('enabled');
$hasLanguage = $model->getMeta()->hasProperty('language');
?>
<div class="btn-group w-100 rounded-4" data-admin-select-submit="true" data-admin-select>
  <button class="btn btn-primary btn-block text-start px-3 admin-select-button"
          data-mdb-dropdown-init
          data-mdb-ripple-init
          data-admin-select-title>
  </button>
  <button
    type="button"
    class="btn btn-primary dropdown-toggle dropdown-toggle-split"
    data-mdb-dropdown-init
    data-mdb-ripple-init></button>
  <input name="filter[<?php echo $filter['by']; ?>]"
         value="<?php echo $filter['value']; ?>"
         type="hidden"
         data-admin-select-input/>
  <ul class="dropdown-menu w-100 admin-select-searchable overflow-y-auto">
    <li>
      <a class="dropdown-item" role="button" data-admin-select-option>
        <?php echo $title; ?>
      </a>
    </li>
    <li class="p-2">
      <div class="form-outline" data-mdb-input-init>
        <input type="text" class="form-control" data-admin-select-search/>
        <label class="form-label"><?php echo Locale::t('Search'); ?></label>
      </div>
    </li>
    <?php foreach ($model::fetchAll() as $rec) : ?>
      <li>
        <a class="dropdown-item"
           role="button"
           data-value="<?php echo $rec->id; ?>"
           data-admin-select-option
           <?php if ($filter['value'] === $rec->id) : ?>data-selected<?php endif; ?>>
          <div class="d-flex justify-content-between align-items-center">
            <div>
              <?php if ($hasImage) : ?>
                <div class="admin-select-image bg-image rounded-4 me-3"
                     style="background-image: url('<?php echo $rec->image?->getSrc(); ?>')"></div>
              <?php endif; ?>
              <span
                class="flex-grow-1 text-wrap max-lines-2 pe-3 admin-select-button-title"><?php echo $rec->$field; ?></span>
            </div>
            <div class="d-flex align-items-center gap-2 justify-content-between">
              <?php if ($hasEnabled) : ?>
                <i
                  class="fas fa-<?php if ($rec->enabled) : ?>check text-success<?php else: ?>ban text-danger<?php endif; ?>"></i>
              <?php endif; ?>
              <?php if ($hasLanguage) : ?>
                <span><?php echo $rec->language->key; ?></span>
              <?php endif; ?>
            </div>
          </div>
        </a>
      </li>
    <?php endforeach; ?>
  </ul>
</div>