<?php

use Air\Cookie;
use Air\Core\Front;
use Air\View\View;

/** @var View $this */

/** @var string $tiny */
$tiny = Front::getInstance()->getConfig()['air']['admin']['tiny'];

/** @var string $fonts */
$fonts = Front::getInstance()->getConfig()['air']['admin']['fonts'];

/** @var string $title */
$title = Front::getInstance()->getConfig()['air']['admin']['title'];

/** @var string $theme */
$theme = Cookie::get('theme') ?? 'dark';

/** @var string $title */
$lang = Front::getInstance()->getConfig()['air']['admin']['locale'];

/** @var string $favicon */
$favicon = Front::getInstance()->getConfig()['air']['admin']['favicon'];

/** @var bool $isSelectControl */
$isSelectControl = $this->isSelectControl ?? false;

/** @var array $adminConfig */
$adminConfig = Front::getInstance()->getConfig()['air']['admin'];
?>
<!DOCTYPE html>
<html lang="<?php echo $lang; ?>">
<head>
  <?php

  echo tag('link', attributes: ['rel' => 'icon', 'href' => $favicon]);
  echo tag('meta', attributes: ['charset' => 'UTF-8']);
  echo tag('meta', attributes: ['name' => 'viewport', 'content' => 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0']);
  echo tag('title', content: $adminConfig['title']);

  echo $this->base();
  ?>

  <script>
    window.fontsUrl = '<?php echo $fonts; ?>';
    const locale = (key) => {
      const value = (<?php echo json_encode(\Air\Crud\Locale::phrases(), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE); ?>)[key];
      if (!value) {
        const ph = JSON.parse(localStorage.getItem('phrases')) || {};
        ph[key] = key;
        localStorage.setItem('phrases', JSON.stringify(ph));
      }
      return value || key;
    };
  </script>

  <?php echo $this->asset([
    'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200',
    'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap',
    'https://cdn.tiny.cloud/1/' . $tiny . '/tinymce/6/tinymce.min.js',

    'vendor/fa/css/all.css',
    'vendor/fa/css/sharp-duotone-solid.css',
    'vendor/fa/css/sharp-light.css',
    'vendor/fa/css/sharp-regular.css',
    'vendor/fa/css/sharp-solid.css',
    'vendor/fa/css/sharp-thin.css',

    'vendor/mdb/light.css',
    'vendor/mdb/mdb.js',

    'vendor/jq.js',
    'vendor/sortable.js',

    'vendor/dt-picker/dt.css',
    'vendor/dt-picker/dt.js',

    'vendor/jq-ui/jquery-ui.css',
    'vendor/jq-ui/jquery-ui.js',

    'css/blur.css',
    'css/max-lines.css',
    'css/scrollbar.css',
    'css/transition.css',
    'css/rotate.css',
    'css/bg-image.css',
    'css/z-index.css',
    'css/ratio.css',

    'css/admin.css',

    'js/mdb.js',
    'js/clipboard.js',
    'js/modal/modal.js',
    'js/wait.js',
    'js/cookie.js',
    'js/theme.js',
    'js/loader.js',
    'js/notify.js',
    'js/nav.js',
    'js/context-menu.js',
    'js/tab.js',
    'js/select.js',
    'js/accordion.js',
    'js/tiny.js',
    'js/embed/embed.js',
    'js/file/file.js',
    'js/datepicker.js',
    'js/bg-image.js',
    'js/crud-locale.js',

    'js/crud-table.js',
    'js/crud-form.js',
    'js/crud-positioning.js',

    'js/crud-elements/multiple-key-value.js',
    'js/crud-elements/multiple-text.js',
    'js/crud-elements/multiple-model.js',
    'js/crud-elements/rich-content.js',
    'js/crud-elements/storage.js',
    'js/crud-elements/embed.js',
    'js/crud-elements/page.js',
    'js/crud-elements/group-multiple.js',
    'js/crud-elements/page-multiple.js',
    'js/crud-elements/meta.js',
    'js/crud-elements/icon.js',
    'js/crud-elements/fa-icon.js',

    'js/general.js',

    '/' . $fonts . '/css'
  ]); ?>
</head>
<body data-mdb-theme="<?php echo $theme; ?>" class="overflow-hidden">
<main class="vh-100 vw-100 d-flex">
  <?php if (!$isSelectControl) : ?>
    <div class="bg-body-tertiary overflow-hidden overflow-y-auto menu">
      <?php echo $this->partial('common/nav'); ?>
    </div>
  <?php endif; ?>
  <div class="w-100 overflow-hidden overflow-y-auto" data-admin-layout-main>
    <?php echo $this->getContent(); ?>
  </div>
</main>
</body>
</html>