<?php

use Air\Cookie;
use Air\Core\Front;

/** @var string $tiny */
$tiny = Front::getInstance()->getConfig()['air']['admin']['tiny'];

/** @var string $fonts */
$fonts = Front::getInstance()->getConfig()['air']['admin']['fonts'];


/** @var string $title */
$title = Front::getInstance()->getConfig()['air']['admin']['title'];

/** @var string $theme */
$theme = Cookie::get('theme') ?? 'dark';

$isSelectControl = $this->isSelectControl ?? false;
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <?php
  echo $this->partial('common/head');
  echo $this->asset([

    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css',
    'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200',
    'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap',
    'https://cdn.tiny.cloud/1/' . $tiny . '/tinymce/6/tinymce.min.js',

    'vendor/mdb/light.css',
    'vendor/mdb/mdb.js',

    'vendor/jq.js',
    'vendor/sortable.js',

    'vendor/dt-picker/dt.css',
    'vendor/dt-picker/dt.js',

    'vendor/jq-ui/jquery-ui.css',
    'vendor/jq-ui/jquery-ui.js',

    'css/blur.css',
    'css/max-lines.css',
    'css/scrollbar.css',
    'css/transition.css',
    'css/rotate.css',
    'css/bg-image.css',
    'css/z-index.css',
    'css/ratio.css',

    'css/admin.css',

    'js/mdb.js',
    'js/clipboard.js',
    'js/modal/modal.js',
    'js/wait.js',
    'js/cookie.js',
    'js/theme.js',
    'js/loader.js',
    'js/notify.js',
    'js/nav.js',
    'js/context-menu.js',
    'js/tab.js',
    'js/select.js',
    'js/accordion.js',
    'js/tiny.js',
    'js/embed/embed.js',
    'js/file/file.js',
    'js/datepicker.js',
    'js/bg-image.js',

    'js/crud-table.js',
    'js/crud-form.js',
    'js/crud-positioning.js',

    'js/crud-elements/multiple-key-value.js',
    'js/crud-elements/multiple-text.js',
    'js/crud-elements/multiple-model.js',
    'js/crud-elements/rich-content.js',
    'js/crud-elements/storage.js',
    'js/crud-elements/embed.js',
    'js/crud-elements/page.js',
    'js/crud-elements/group-multiple.js',
    'js/crud-elements/page-multiple.js',
    'js/crud-elements/meta.js',
    'js/crud-elements/icon.js',

  ]); ?>
  <link href="/<?php echo $fonts; ?>/css" rel="stylesheet"/>
</head>
<body data-mdb-theme="<?php echo $theme; ?>" class="overflow-hidden">
<main class="vh-100 vw-100 d-flex">
  <?php if (!$isSelectControl) : ?>
    <div class="bg-body-tertiary overflow-hidden overflow-y-auto menu">
      <?php echo $this->partial('common/nav'); ?>
    </div>
  <?php endif; ?>
  <div class="w-100 overflow-hidden overflow-y-auto" data-admin-layout-main>
    <?php echo $this->getContent(); ?>
  </div>
</main>
</body>
</html>