<?php

use Air\Form\Element\Text;

/** @var Text $element */
$element = $this->element;
?>
<div class="form-check form-switch">
  <input class="form-check-input"
         type="checkbox"
         role="switch"
         value="1"
         id="<?php echo $element->getName(); ?>"
         name="<?php echo $element->getName(); ?>"
    <?php if ($element->getValue()) : ?> checked="checked" <?php endif; ?>>
</div>