<?php

use Air\Core\Front;
use Air\Map;
use Air\Model\Paginator;

/** @var int $page */
$page = $this->page;

/** @var Paginator $paginator */
$paginator = $this->paginator;

/** @var array $controls */
$controls = $this->controls;

/** @var bool $isSelectControl */
$isSelectControl = $this->isSelectControl;

/** @var string $controller */
$controller = $this->controller;

if ((!$isSelectControl && !count($controls)) || !$paginator->count()) {
  return;
}

$returnUrl = Front::getInstance()->getRequest()->getUri();

$toJson = function ($row) {
  $data = Map::execute($row, [
    'id',
    'title',
    'enabled',
    'systemTitle',
    'image' => function ($row) {
      if (!$row->getMeta()->hasProperty('image')) {
        return null;
      }
      return ['src' => $row->image?->getSrc()];
    },
  ]);

  return htmlspecialchars(json_encode($data), ENT_QUOTES, 'UTF-8');
};
?>

<?php foreach ($paginator->getItems() as $row) : ?>

  <ul class="dropdown-menu shadow-5-strong" data-admin-contextmenu-target="<?php echo $row->id; ?>">

    <?php if (!$isSelectControl) : ?>

      <?php foreach (($controls ?? []) as $control) : ?>
        <?php if (($control['type'] ?? false) === 'custom') : ?>
          <?php $customControl = $control['source']($row); ?>
          <?php if ($customControl) : ?>
            <li>
              <a class="dropdown-item"
                <?php if (($customControl['confirm'] ?? false)) : ?>
                  data-confirm="<?php echo $customControl['confirm']; ?>"
                <?php endif; ?>
                 href="<?php echo $customControl['url']; ?>">
                <i class="fas fa-<?php echo $customControl['icon']; ?> me-1"></i> <?php echo $customControl['title']; ?>
              </a>
            </li>
          <?php endif; ?>

        <?php elseif (($control['type'] ?? false) === 'view') : ?>
          <li>
            <a class="dropdown-item"
               role="button"
               data-admin-table-view-model="<?php echo $controller; ?>"
               data-admin-table-view-id="<?php echo $row->id; ?>">
              <i class="fas fa-eye me-1"></i> <?php echo \Air\Crud\Locale::t('View'); ?>
            </a>
          </li>

        <?php elseif (($control['type'] ?? false) === 'edit') : ?>
          <li>
            <a class="dropdown-item"
               href="<?php echo $this->uri(['controller' => $controller, 'action' => 'manage'], ['id' => $row->id, 'returnUrl' => $returnUrl]); ?>">
              <i class="fas fa-edit me-1"></i> <?php echo \Air\Crud\Locale::t('Manage'); ?>
            </a>
          </li>

        <?php elseif (($control['type'] ?? false) === 'copy') : ?>
          <li>
            <a class="dropdown-item"
               role="button"
               data-admin-table-row-copy="<?php echo $this->uri(['controller' => $controller, 'action' => 'copy'], ['id' => $row->id]); ?>">
              <i class="fas fa-copy me-1"></i> <?php echo \Air\Crud\Locale::t('Copy?'); ?>
            </a>
          </li>

        <?php elseif (($control['type'] ?? false) == 'enabled' && $row->getMeta()->hasProperty('enabled')) : ?>

          <?php if ($row->enabled) : ?>
            <li>
              <a class="dropdown-item"
                 role="button"
                 data-confirm="<?php echo \Air\Crud\Locale::t('Disable record?'); ?>"
                 data-admin-table-row-activity="<?php echo $this->uri(['controller' => $controller, 'action' => 'setEnabled'], ['enabled' => 0, 'id' => $row->id]); ?>">
                <i class="fas fa-ban me-1"></i> <?php echo \Air\Crud\Locale::t('Disable?'); ?>
              </a>
            </li>

          <?php else: ?>
            <li>
              <a class="dropdown-item"
                 role="button"
                 data-confirm="<?php echo \Air\Crud\Locale::t('Enable record?'); ?>"
                 data-admin-table-row-activity="<?php echo $this->uri(['controller' => $controller, 'action' => 'setEnabled'], ['enabled' => 1, 'id' => $row->id]); ?>">
                <i class="fas fa-check me-1"></i> <?php echo \Air\Crud\Locale::t('Enable?'); ?>
              </a>
            </li>
          <?php endif; ?>

        <?php elseif (($control['type'] ?? false) == 'separator') : ?>
          <li class="dropdown-divider"></li>

        <?php elseif ($control['url'] ?? false) : ?>

          <?php if (is_array($control['url'])) : ?>
            <?php $control['url'] = urldecode($this->uri($control['url'], ['id' => $row->id], true)); ?>
          <?php endif; ?>

          <li>
            <a class="dropdown-item"
              <?php if ($control['confirm'] ?? false) : ?>
                href="<?php echo $control['url']; ?>"
                data-confirm="<?php echo $control['confirm']; ?>"
                role="button"
              <?php else: ?>
                href="<?php echo $control['url']; ?>"
              <?php endif; ?>
            >
              <?php if ($control['icon'] ?? false) : ?>
                <i class="fa fa-<?php echo $control['icon'] ?? false; ?> me-1"></i>
              <?php endif; ?>
              <?php echo $control['title']; ?>
            </a>
          </li>

        <?php endif; ?>
      <?php endforeach; ?>

    <?php elseif ($isSelectControl) : ?>

      <li>
        <a class="dropdown-item"
           role="button"
           data-admin-table-row-select="<?php echo $row->id; ?>">
          <div class="d-none" data-admin-table-row-object><?php echo $toJson($row); ?></div>
          <i class="fas fa-check me-1"></i> <?php echo \Air\Crud\Locale::t('Select'); ?>
        </a>
      </li>

    <?php endif; ?>

  </ul>

<?php endforeach; ?>
