<?php

use Air\Cookie;

/** @var string $title */
$title = $this->title;

/** @var string $theme */
$theme = Cookie::get('theme') ?? 'dark';
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <?php
  echo $this->partial('common/head');
  echo $this->asset([
    'https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap',
    'vendor/mdb/light.css',
    'vendor/mdb/mdb.js',
    'vendor/jq.js',
    'css/blur.css',
    'css/scrollbar.css',
    'css/transition.css',
    'js/mdb.js',
    'js/wait.js',
    'js/loader.js',
    'js/login.js'
  ]); ?>
</head>
<body data-mdb-theme="<?php echo Cookie::get('theme') ?? 'dark'; ?>">
<div class="container">
  <div class="row justify-content-center mt-4">
    <div class="col-12 col-lg-4 mt-4">
      <div class="card fade transition mt-4">
        <div class="card-body">
          <h1 class="mb-4"><?php echo $title; ?></h1>
          <form method="post">
            <div data-mdb-input-init class="form-outline mb-4">
              <input type="text" id="login" class="form-control" name="login" required/>
              <label class="form-label" for="login">Login</label>
            </div>
            <div data-mdb-input-init class="form-outline mb-4">
              <input type="password" id="password" class="form-control" required name="password"/>
              <label class="form-label" for="password">Password</label>
            </div>
            <button data-mdb-ripple-init type="submit" class="btn btn-primary btn-block">Sign in</button>
            <div class="text-danger bg-danger-subtle rounded-4 mt-4 p-4 py-3 d-none" data-error>
              Login or password are incorrect
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</html>
