<?php

use Air\Core\Front;

$adminConfig = Front::getInstance()->getConfig()['air']['admin'];
$storageConfig = Front::getInstance()->getConfig()['air']['storage'];
?>

<meta charset="utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0'/>

<title><?php echo $adminConfig['title']; ?></title>