<?php

/** @var string $title */

use Air\Core\Front;

$title = $this->title;

/** @var string $icon */
$icon = $this->icon;

/** @var string $mode */
$mode = $this->mode;

$filter = $this->filter ?? [];

/** @var bool $manageable */
$manageable = $this->manageable;

$request = Front::getInstance()->getRequest();

/** @var bool $positioning */
$positioning = $this->positioning;

/** @var bool $isQuickManage */
$isQuickManage = $this->isQuickManage;

/** @var bool $isSingleControl */
$isSingleControl = $this->isSingleControl;

/** @var bool $isPositioningControl */
$isPositioningControl = $this->isPositioningControl;

$export = $this->export ?? [];
$headerButtons = $this->headerButtons ?? [];

/** @var string $controller */
$controller = $this->controller;
?>
<div class="p-3 position-sticky top-0 z-i-1001 header">
  <div class="card position-sticky w-100">
    <div class="card-body p-3 d-flex justify-content-between align-items-center">

      <h5 class="m-0 p-0">
        <?php if ($icon) : ?>
          <i class="fas fa-<?php echo $icon; ?> me-1"></i>
        <?php endif; ?>
        <?php echo $title; ?>
      </h5>

      <div class="d-flex">
        <?php if ($mode === 'manage') : ?>

          <?php if (!$isQuickManage) : ?>
            <a class="btn btn-secondary ms-2 px-3" data-mdb-ripple-init data-admin-from-manage-back>
              <i class="fa fa-arrow-left me-1"></i>
              <?php echo \Air\Crud\Locale::t('Go back'); ?>
            </a>
          <?php endif; ?>

          <a class="btn btn-primary ms-2 px-3" data-mdb-ripple-init data-admin-from-manage-save>
            <i class="fa fa-save me-1"></i>
            <?php echo \Air\Crud\Locale::t('Save (CTRL+S)'); ?>
          </a>
        <?php endif; ?>

        <?php if (count($filter)) : ?>
          <a href="<?php echo $this->uri(['controller' => $controller]); ?>" class="btn btn-danger ms-2 px-3"
             data-mdb-ripple-init>
            <i class="fa fa-filter me-1"></i>
            <?php echo \Air\Crud\Locale::t('Clear filter'); ?>
          </a>
        <?php endif; ?>

        <?php if ($manageable) : ?>
          <a
            href="<?php echo $this->uri(['controller' => $controller, 'action' => 'manage'], ['returnUrl' => $request->getUri()]); ?>"
            class="btn btn-primary ms-2 px-3"
            data-mdb-ripple-init>
            <i class="fas fa-plus me-1"></i>
            <?php echo \Air\Crud\Locale::t('Add'); ?>
          </a>
        <?php endif; ?>

        <?php if ($positioning && !$isPositioningControl) : ?>
          <a class="btn btn-info ms-2 px-3"
             href="<?php echo $this->uri(['controller' => $controller, 'action' => 'position'], $request->getParams()); ?>"
             data-mdb-ripple-init>
            <i class="fas fa-sort me-1"></i>
            <?php echo \Air\Crud\Locale::t('Sort'); ?>
          </a>
        <?php endif; ?>

        <?php if ($isPositioningControl) : ?>

          <a class="btn btn-danger ms-2 px-3" data-mdb-ripple-init data-admin-from-positioning-reset>
            <i class="fa fa-power-off me-1"></i>
            <?php echo \Air\Crud\Locale::t('Reset'); ?>
          </a>

          <a class="btn btn-primary ms-2 px-3" data-mdb-ripple-init data-admin-from-positioning-save>
            <i class="fa fa-save me-1"></i>
            <?php echo \Air\Crud\Locale::t('Save (CTRL+S)'); ?>
          </a>

        <?php endif; ?>

        <?php if (count($export)) : ?>
          <a
            href="<?php echo $this->uri(['controller' => $controller, 'action' => 'export'], $request->getParams()); ?>"
            class="btn btn-secondary ms-2 px-3"
            data-mdb-ripple-init
            data-force="true">
            <i class="fas fa-download me-1"></i>
            <?php echo \Air\Crud\Locale::t('Export'); ?>
          </a>
        <?php endif; ?>

        <?php foreach ($headerButtons as $headerButton) : ?>
          <?php $url = is_array($headerButton['url']) ? $this->uri($headerButton['url'], $headerButton['params'] ?? []) : $headerButton['url']; ?>
          <a class="btn btn-<?php echo $headerButton['style']['color'] ?? 'primary'; ?> ms-2 px-3"
            <?php if ($headerButton['confirm'] ?? false) : ?>
              href="<?php echo $url; ?>"
              data-confirm="<?php echo $headerButton['confirm']; ?>"
            <?php else: ?>
              href="<?php echo $url; ?>"
            <?php endif; ?>
             data-mdb-ripple-init>
            <?php if ($headerButton['style']['icon'] ?? false) : ?>
              <i class="fas fa-<?php echo $headerButton['style']['icon']; ?>"></i>
            <?php endif; ?>
            <?php echo $headerButton['title']; ?>
          </a>
        <?php endforeach; ?>

      </div>
    </div>
  </div>
</div>