<?php

use Air\Cookie;
use Air\Core\Front;

/** @var string $title */
$title = Front::getInstance()->getConfig()['air']['admin']['title'];

/** @var array $menu */
$menu = Front::getInstance()->getConfig()['air']['admin']['menu'];

/** @var string $logo */
$logo = Front::getInstance()->getConfig()['air']['admin']['logo'];

/** @var string $theme */
$theme = Cookie::get('theme') ?? 'dark';

/** @var string $logout */
$logout = $this->uri([
  'controller' => Front::getInstance()->getConfig()['air']['admin']['auth']['route'],
  'action' => 'logout'
]);

/** @var string $storage */
$storage = $this->uri(['controller' => Front::getInstance()->getConfig()['air']['storage']['route']]);

/** @var string $system */
$system = $this->uri(['controller' => Front::getInstance()->getConfig()['air']['admin']['system']]);

/** @var string $logs */
$logs = $this->uri(['controller' => Front::getInstance()->getConfig()['air']['logs']['route']]);

/** @var string $administrators */
$administrators = $this->uri(['controller' => Front::getInstance()->getConfig()['air']['admin']['manage']]);

/** @var string $administratorsHistory */
$administratorsHistory = $this->uri(['controller' => Front::getInstance()->getConfig()['air']['admin']['history']]);

/** @var string $fonts */
$fonts = $this->uri(['controller' => Front::getInstance()->getConfig()['air']['admin']['fonts']]);
?>

<div class="d-flex flex-column h-100">
  <div class="d-flex flex-column flex-grow-1">

    <div class="p-3 position-sticky top-0 z-1 header-menu">
      <div class="card position-sticky w-100">
        <div class="card-body p-3 d-flex justify-content-between align-items-center"
             href="<?php echo $this->uri(['controller' => 'index']); ?>"
             role="button">
          <div class="d-flex align-items-center">
            <div class="logo bg-image bg-image-contain me-2" data-admin-async-image="<?php echo $logo; ?>"></div>
            <h5 class="p-0 m-0"><?php echo $title; ?></h5>
          </div>
        </div>
      </div>
    </div>


    <div class="px-3" data-admin-accordion>

      <?php foreach ($menu as $subMenu) : ?>

        <div class="mb-3">

          <div class="rounded-4 p-3 d-flex justify-content-between transition-1 shadow-5-strong"
               role="button"
               data-admin-accordion-nav>
            <h6 class="m-0 admin-nav-section">
              <i class="fas fa-<?php echo $subMenu['icon']; ?> me-1"></i>
              <?php echo $subMenu['title']; ?>
            </h6>
            <i class="fas fa-chevron-right transition-2" data-admin-accordion-nav-icon></i>
          </div>

          <div class="transition-2 rounded-bottom-3 overflow-hidden"
               data-admin-accordion-content>
            <div>
              <?php foreach ($subMenu['items'] as $subMenuItems) : ?>
                <a class="btn btn-link btn-block text-start btn-lg text-capitalize m-0 px-3 admin-nav-link"
                   href="<?php echo $this->uri($subMenuItems['url'], [], true); ?>"
                   data-mdb-ripple-init>
                  <i class="fas fa-<?php echo $subMenuItems['icon']; ?> me-1"></i>
                  <?php echo $subMenuItems['title']; ?>
                </a>
              <?php endforeach; ?>
            </div>
          </div>

        </div>

      <?php endforeach; ?>
    </div>

    <div class="p-3 pt-0 overflow-hidden overflow-y-auto d-none">
      <?php foreach ($menu as $subMenu) : ?>
        <div class="nav-container mb-2">
          <div
            class="rounded-4 p-3 d-flex align-items-center justify-content-between bg-body-secondary transition-1"
            role="button"
            data-mdb-ripple-init
          >
            <h6 class="m-0 p-0 w-100">
              <i class="fas fa-<?php echo $subMenu['icon']; ?> me-1"></i>
              <?php echo $subMenu['title']; ?>
            </h6>
            <div class="d-flex h-100 w-25 align-items-center justify-content-end">
              <i class="fas fa-chevron-up lh-1 transition-1" data-nav-icon></i>
            </div>
          </div>
          <div class="transition-2 mt-2 overflow-hidden"
               style="max-height: 0"
               data-nav-submenu>
            <?php foreach ($subMenu['items'] as $subMenuItems) : ?>
              <a class="btn btn-link btn-block text-start btn-lg text-capitalize m-0"
                 href="<?php echo $this->uri($subMenuItems['url'], [], true); ?>"
                 data-mdb-ripple-init>
                <i class="fas fa-<?php echo $subMenuItems['icon']; ?> me-1"></i>
                <?php echo $subMenuItems['title']; ?>
              </a>
            <?php endforeach; ?>
          </div>
        </div>
      <?php endforeach; ?>
    </div>
  </div>

  <div class="card">
    <div class="card-body p-3">
      <div class="btn-group w-100">
        <button
          type="button"
          class="btn btn-primary dropdown-toggle"
          data-mdb-dropdown-init
          data-mdb-ripple-init>
          <i class="fas fa-power-off me-1"></i>
          Settings
        </button>
        <ul class="dropdown-menu">
          <li class="d-flex">
            <a class="dropdown-item" role="button" onclick="theme.set('dark')">
              <i class="fas fa-moon me-1 text-primary-emphasis"></i> Night
            </a>
            <a class="dropdown-item" role="button" onclick="theme.set('air')">
              <i class="fas fa-sun me-1 text-warning-emphasis"></i> Day
            </a>
          </li>
          <li class="dropdown-divider mt-0 pt-0"></li>
          <li>
            <a class="dropdown-item" href="<?php echo $storage; ?>">
              <i class="fas fa-folder me-1"></i> File storage
            </a>
          </li>
          <li>
            <a class="dropdown-item" href="<?php echo $fonts; ?>">
              <i class="fas fa-font me-1"></i> Fonts
            </a>
          </li>
          <li>
            <a class="dropdown-item" href="<?php echo $system; ?>">
              <i class="fas fa-pie-chart me-1"></i> System monitor
            </a>
          </li>
          <li class="dropdown-divider"></li>
          <li>
            <a class="dropdown-item" href="<?php echo $logs; ?>">
              <i class="fas fa-list me-1"></i> Logs
            </a>
          </li>
          <li class="dropdown-divider"></li>
          <li>
            <a class="dropdown-item" href="<?php echo $administrators; ?>">
              <i class="fas fa-users me-1"></i> Administrators
            </a>
          </li>
          <li>
            <a class="dropdown-item" href="<?php echo $administratorsHistory; ?>">
              <i class="fas fa-clock me-1"></i> Administrator history
            </a>
          </li>
          <li class="dropdown-divider"></li>
          <li>
            <a class="dropdown-item text-danger-emphasis"
               href="<?php echo $logout; ?>"
               data-force="true"
               data-confirm="Do you really want to sign out?1">
              <i class="fa fa-sign-out me-1"></i> Sign out
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>