<?php

use Air\Cookie;
use Air\Core\Front;

/**
 * @param mixed $value
 * @param mixed $default
 * @return mixed
 */
$value = function (mixed $value, mixed $default = '') {
  return $value ?: $default;
};

$route = function (?string $controller = null) {
  return $controller ? $this->uri(['controller' => $controller]) : null;
};

$config = Front::getInstance()->getConfig()['air'];

/** @var string $title */
$title = $value($config['admin']['title'] ?? null, 'AirCms');

/** @var array $menu */
$menu = $value($config['admin']['menu'] ?? null, []);

/** @var string $logo */
$logo = $value($config['admin']['logo'] ?? null);

/** @var string $theme */
$theme = Cookie::get('theme') ?? 'dark';

/** @var string $logout */
$logout = $this->uri(['controller' => $config['admin']['auth']['route'], 'action' => 'logout']);

/** @var string $storage */
$storage = $route($config['storage']['route'] ?? null);

/** @var string $system */
$system = $route($config['admin']['system'] ?? null);

/** @var string $logs */
$logs = $route($config['logs']['route'] ?? null);

/** @var string $administrators */
$administrators = $route($config['admin']['manage'] ?? null);

/** @var string $administratorsHistory */
$administratorsHistory = $route($config['admin']['history'] ?? null);

/** @var string $fonts */
$fonts = $route($config['admin']['fonts'] ?? null);

/** @var string $codes */
$codes = $route($config['admin']['codes'] ?? null);

/** @var string $languages */
$languages = $route($config['admin']['languages'] ?? null);

/** @var string $phrases */
$phrases = $route($config['admin']['phrases'] ?? null);

/** @var string $robotsTxt */
$robotsTxt = $route($config['admin']['robotsTxt'] ?? null);

/** @var string $cache */
$cache = $route($config['admin']['cache'] ?? null);
?>

<div class="d-flex flex-column h-100">
  <div class="d-flex flex-column flex-grow-1">

    <div class="p-3 position-sticky top-0 z-1 header-menu">
      <div class="card position-sticky w-100">
        <div class="card-body p-3 d-flex justify-content-between align-items-center"
             href="<?php echo $this->uri(['controller' => 'index']); ?>"
             role="button">
          <div class="d-flex align-items-center">
            <div class="logo bg-image bg-image-contain me-2" data-admin-async-image="<?php echo $logo; ?>"></div>
            <h5 class="p-0 m-0"><?php echo $title; ?></h5>
          </div>
        </div>
      </div>
    </div>


    <div class="px-3" data-admin-accordion>

      <?php foreach ($menu as $subMenu) : ?>

        <div class="mb-3">

          <div class="rounded-4 p-3 d-flex justify-content-between transition-1 shadow-5-strong"
               role="button"
               data-admin-accordion-nav>
            <h6 class="m-0 admin-nav-section">
              <i class="fas fa-<?php echo $subMenu['icon']; ?> me-1"></i>
              <?php echo $subMenu['title']; ?>
            </h6>
            <i class="fas fa-chevron-right transition-2" data-admin-accordion-nav-icon></i>
          </div>

          <div class="transition-2 rounded-bottom-3 overflow-hidden"
               data-admin-accordion-content>
            <div>
              <?php foreach ($subMenu['items'] as $subMenuItems) : ?>

                <?php if ($subMenuItems === 'divider') : ?>
                  <div class="dropdown-divider"></div>
                  <?php continue; ?>
                <?php endif; ?>

                <a class="btn btn-link btn-block text-start btn-lg text-capitalize m-0 px-3 admin-nav-link"
                   href="<?php echo $this->uri($subMenuItems['url'], [], true); ?>"
                   data-mdb-ripple-init>
                  <i class="fas fa-<?php echo $subMenuItems['icon']; ?> me-1"></i>
                  <?php echo $subMenuItems['title']; ?>
                </a>
              <?php endforeach; ?>
            </div>
          </div>

        </div>

      <?php endforeach; ?>
    </div>
  </div>

  <div class="card">
    <div class="card-body p-3">
      <div class="btn-group w-100">
        <button
          type="button"
          class="btn btn-primary dropdown-toggle"
          data-mdb-dropdown-init
          data-mdb-ripple-init>
          <i class="fas fa-power-off me-1"></i>
          <?php echo \Air\Crud\Locale::t('Settings'); ?>
        </button>
        <ul class="dropdown-menu">
          <li class="d-flex">
            <a class="dropdown-item" role="button" onclick="theme.set('dark')">
              <i class="fas fa-moon me-1 text-primary-emphasis"></i> <?php echo \Air\Crud\Locale::t('Night'); ?>
            </a>
            <a class="dropdown-item" role="button" onclick="theme.set('air')">
              <i class="fas fa-sun me-1 text-warning-emphasis"></i> <?php echo \Air\Crud\Locale::t('Day'); ?>
            </a>
          </li>
          <li class="dropdown-divider mt-0 pt-0"></li>
          <?php if ($storage) : ?>
            <li>
              <a class="dropdown-item" href="<?php echo $storage; ?>">
                <i class="fas fa-folder me-1"></i> <?php echo \Air\Crud\Locale::t('File storage'); ?>
              </a>
            </li>
          <?php endif; ?>
          <?php if ($fonts) : ?>
            <li>
              <a class="dropdown-item" href="<?php echo $fonts; ?>">
                <i class="fas fa-font me-1"></i> <?php echo \Air\Crud\Locale::t('Fonts'); ?>
              </a>
            </li>
          <?php endif; ?>
          <?php if ($system) : ?>
            <li>
              <a class="dropdown-item" href="<?php echo $system; ?>">
                <i class="fas fa-pie-chart me-1"></i> <?php echo \Air\Crud\Locale::t('System monitor'); ?>
              </a>
            </li>
          <?php endif; ?>
          <?php if ($languages && $phrases) : ?>
            <li class="dropdown-divider"></li>
            <li>
              <a class="dropdown-item" href="<?php echo $languages; ?>">
                <i class="fas fa-globe me-1"></i> <?php echo \Air\Crud\Locale::t('Languages'); ?>
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="<?php echo $phrases; ?>">
                <i class="fas fa-language me-1"></i> <?php echo \Air\Crud\Locale::t('Phrases'); ?>
              </a>
            </li>
          <?php endif; ?>
          <?php if ($logs) : ?>
            <li class="dropdown-divider"></li>
            <li>
              <a class="dropdown-item" href="<?php echo $logs; ?>">
                <i class="fas fa-list me-1"></i> <?php echo \Air\Crud\Locale::t('Logs'); ?>
              </a>
            </li>
          <?php endif; ?>
          <?php if ($administrators) : ?>
            <li class="dropdown-divider"></li>
            <li>
              <a class="dropdown-item" href="<?php echo $administrators; ?>">
                <i class="fas fa-users me-1"></i> <?php echo \Air\Crud\Locale::t('Administrators'); ?>
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="<?php echo $administratorsHistory; ?>">
                <i class="fas fa-clock me-1"></i> <?php echo \Air\Crud\Locale::t('Administrator history'); ?>
              </a>
            </li>
            <li class="dropdown-divider"></li>
          <?php endif; ?>
          <?php if ($codes) : ?>
            <li>
              <a class="dropdown-item" href="<?php echo $codes; ?>">
                <i class="fas fa-code me-1"></i> <?php echo \Air\Crud\Locale::t('Codes'); ?>
              </a>
            </li>
            <?php if ($robotsTxt) : ?>
              <li>
                <a class="dropdown-item" href="<?php echo $robotsTxt; ?>">
                  <i class="fas fa-robot me-1"></i> <?php echo \Air\Crud\Locale::t('Robots.txt'); ?>
                </a>
              </li>
            <?php endif; ?>
            <li class="dropdown-divider"></li>
          <?php endif; ?>

          <?php if ($cache) : ?>
            <li>
              <a class="dropdown-item text-danger-emphasis"
                 role="button"
                 data-admin-clean-cache
                 data-href="<?php echo $cache; ?>"
                 data-confirm="<?php echo \Air\Crud\Locale::t('Clear cache now?'); ?>">
                <i class="fa fa-trash me-1"></i> <?php echo \Air\Crud\Locale::t('Clean cache'); ?>
              </a>
            </li>
            <li class="dropdown-divider"></li>
          <?php endif; ?>
          <li>
            <a class="dropdown-item text-danger-emphasis"
               href="<?php echo $logout; ?>"
               data-force="true"
               data-confirm="<?php echo \Air\Crud\Locale::t('Do you really want to sign out?'); ?>">
              <i class="fa fa-sign-out me-1"></i> <?php echo \Air\Crud\Locale::t('Sign out'); ?>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>