<?php

use Air\Model\ModelAbstract;
use Air\Model\Paginator;

/** @var Paginator $paginator */
$paginator = $this->paginator;

/** @var array $header */
$header = $this->header;
$title = $this->title ?? '';
?>

<div class="p-3 overflow-hidden overflow-y-auto z-1 content">

  <?php if (strlen($title)) : ?>
    <div class="card position-sticky w-100 mb-3">
      <div class="card-body p-3 d-flex justify-content-between align-items-center">
        <?php echo $title; ?>
      </div>
    </div>
  <?php endif; ?>

  <form data-admin-table-form>

    <?php if ($paginator->count()) : ?>

      <div class="card">
        <div class="card-body p-3">
          <table class="table table-hover align-middle mb-0 rounded-4 overflow-hidden">
            <?php echo $this->partial('table/partial/head'); ?>
            <tbody>
            <?php /** @var ModelAbstract $row */ ?>
            <?php foreach ($paginator->getItems() as $row) : ?>
              <tr>
                <?php echo $this->partial('table/partial/row', ['header' => $header, 'row' => $row]); ?>
              </tr>
            <?php endforeach; ?>
            </tbody>
          </table>
        </div>
      </div>

    <?php else: ?>

      <div class="card">
        <div class="card-body p-3">
          <h6 class="m-0 p-0 text-muted"><?php echo \Air\Crud\Locale::t('No records'); ?></h6>
        </div>
      </div>

    <?php endif; ?>

  </form>
</div>

<script>
  $(document).ready(() => print());
</script>