<?php

use Air\Type\RichContent;

/** @var \Air\Form\Element\RichContent $element */
$element = $this->element;
$name = $element->getName();
?>

<template type="text/html"
        data-admin-form-rich-content-template-name="<?php echo $name; ?>"
        data-admin-form-rich-content-template="<?php echo RichContent::TYPE_HTML; ?>">

  <input type="hidden" name="<?php echo $name; ?>[{{name}}][type]" value="<?php echo RichContent::TYPE_HTML; ?>">
  <textarea name="<?php echo $name; ?>[{{name}}][value]" data-admin-form-tiny></textarea>

</template>