<template type="text/html" data-admin-form-rich-content-template="toolbar">

  <div data-admin-form-rich-content-toolbar>

    <a class="btn btn-primary px-3"
       data-admin-form-rich-content-toolbar-add="file"
       data-mdb-ripple-init
       data-mdb-tooltip-init
       data-mdb-placement="bottom"
       title="Image">
      <i class="fas fa-image"></i>
    </a>

    <a class="btn btn-primary px-3"
       data-admin-form-rich-content-toolbar-add="files"
       data-mdb-ripple-init
       data-mdb-tooltip-init
       data-mdb-placement="bottom"
       title="Images">
      <i class="fas fa-images"></i>
    </a>

    <a class="btn btn-primary px-3"
       data-admin-form-rich-content-toolbar-add="quote"
       data-mdb-ripple-init
       data-mdb-tooltip-init
       data-mdb-placement="bottom"
       title="Quote">
      <i class="fas fa-quote-right"></i>
    </a>

    <a class="btn btn-primary px-3"
       data-admin-form-rich-content-toolbar-add="text"
       data-mdb-ripple-init
       data-mdb-tooltip-init
       data-mdb-placement="bottom"
       title="Text">
      <i class="fas fa-font"></i>
    </a>

    <a class="btn btn-primary px-3"
       data-admin-form-rich-content-toolbar-add="html"
       data-mdb-ripple-init
       data-mdb-tooltip-init
       data-mdb-placement="bottom"
       title="HTML">
      <i class="fas fa-code"></i>
    </a>

    <a class="btn btn-primary px-3"
       data-admin-form-rich-content-toolbar-add="embed"
       data-mdb-ripple-init
       data-mdb-tooltip-init
       data-mdb-placement="bottom"
       title="Embed">
      <i class="fas fa-anchor"></i>
    </a>

  </div>

</template>