<template type="text/html" data-admin-form-rich-content-template="toolbar">

  <div data-admin-form-rich-content-toolbar>

    <a class="btn btn-primary px-3"
       data-admin-form-rich-content-toolbar-add="file"
       data-mdb-ripple-init
       data-mdb-tooltip-init
       data-mdb-placement="bottom"
       title="<?php echo \Air\Crud\Locale::t('Image'); ?>">
      <i class="fas fa-image"></i>
    </a>

    <a class="btn btn-primary px-3"
       data-admin-form-rich-content-toolbar-add="files"
       data-mdb-ripple-init
       data-mdb-tooltip-init
       data-mdb-placement="bottom"
       title="<?php echo \Air\Crud\Locale::t('Images'); ?>">
      <i class="fas fa-images"></i>
    </a>

    <a class="btn btn-primary px-3"
       data-admin-form-rich-content-toolbar-add="quote"
       data-mdb-ripple-init
       data-mdb-tooltip-init
       data-mdb-placement="bottom"
       title="<?php echo \Air\Crud\Locale::t('Quote'); ?>">
      <i class="fas fa-quote-right"></i>
    </a>

    <a class="btn btn-primary px-3"
       data-admin-form-rich-content-toolbar-add="text"
       data-mdb-ripple-init
       data-mdb-tooltip-init
       data-mdb-placement="bottom"
       title="<?php echo \Air\Crud\Locale::t('Text'); ?>">
      <i class="fas fa-font"></i>
    </a>

    <a class="btn btn-primary px-3"
       data-admin-form-rich-content-toolbar-add="html"
       data-mdb-ripple-init
       data-mdb-tooltip-init
       data-mdb-placement="bottom"
       title="<?php echo \Air\Crud\Locale::t('HTML'); ?>">
      <i class="fas fa-code"></i>
    </a>

    <a class="btn btn-primary px-3"
       data-admin-form-rich-content-toolbar-add="embed"
       data-mdb-ripple-init
       data-mdb-tooltip-init
       data-mdb-placement="bottom"
       title="<?php echo \Air\Crud\Locale::t('Embed'); ?>">
      <i class="fas fa-anchor"></i>
    </a>

  </div>

</template>